#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os

def options(opt):
	grp = opt.add_option_group('Client options')

	grp.add_option('--enable-vgui', action = 'store_true', dest = 'USE_VGUI', default = False,
		help = 'Enable VGUI1')
	grp.add_option('--enable-novgui-motd', action = 'store_true', dest = 'USE_NOVGUI_MOTD', default = False,
		help = 'Prefer non-VGUI MOTD when USE_VGUI is enabled')
	grp.add_option('--enable-novgui-scoreboard', action = 'store_true', dest = 'USE_NOVGUI_SCOREBOARD', default = False,
		help = 'Prefer non-VGUI Scoreboard when USE_VGUI is enabled')
	grp.add_option('--disable-goldsrc-support', action = 'store_false', dest = 'GOLDSOURCE_SUPPORT',
		default=True, help = 'disable GoldSource compatibility on i386 Win/Mac/Linux')

	opt.load('vgui')

def configure(conf):
	conf.options.VGUI_DEV = os.path.join('vgui_support', 'vgui-dev') # vgui is in submodule
	conf.env.USE_VGUI = conf.options.USE_VGUI
	conf.env.USE_NOVGUI_MOTD = conf.options.USE_NOVGUI_MOTD
	conf.env.USE_NOVGUI_SCOREBOARD = conf.options.USE_NOVGUI_SCOREBOARD
	conf.env.USE_VOICEMGR = conf.options.USE_VOICEMGR

	if (conf.env.DEST_CPU == 'x86' or (conf.env.DEST_CPU == 'x86_64' and not conf.options.ALLOW64)) and conf.env.DEST_OS in ['win32', 'linux', 'darwin']:
		conf.env.GOLDSOURCE_SUPPORT = conf.options.GOLDSOURCE_SUPPORT
	else:
		conf.env.GOLDSOURCE_SUPPORT = False

	if conf.env.GOLDSOURCE_SUPPORT and not conf.env.DEST_OS == 'win32':
		conf.check_cc(lib='dl')

	if conf.env.USE_VGUI:
		conf.load('vgui')
		if not conf.check_vgui():
			conf.fatal('VGUI was enabled but VGUI cannot be used')

def build(bld):
	libs = ['vcs_info']
	defines = ['CLIENT_DLL']
	defines += bld.env.EXPORT_DEFINES_LIST
	includes = Utils.to_list('. hl/ ../dlls ../dlls/wpn_shared ../common ../engine ../pm_shared ../game_shared ../public dmc ../dlls/dmc ../dlls/dmc .. ../dlls/aghl ../dlls/3wave')

	source = [
	'3wave/CTF_FlagStatus.cpp',
	'3wave/CTF_HudMessage.cpp',
	'dmc/DMC_Teleporters.cpp',
	'ev_hldm.cpp',
	'../dlls/dmc/quake_gun.cpp',
	'../dlls/dmc/quake_weapons_all.cpp',
	'quake/quake_baseentity.cpp',
	'quake/quake_events.cpp',
	'quake/quake_objects.cpp',
	'quake/quake_weapons.cpp',
	'ammo.cpp',
	'ammo_secondary.cpp',
	'ammohistory.cpp',
	'battery.cpp',
	'cdll_int.cpp',
	'com_weapons.cpp',
	'death.cpp',
	'demo.cpp',
	'entity.cpp',
	'ev_common.cpp',
	'events.cpp',
#	'flashlight.cpp',
	'GameStudioModelRenderer.cpp',
	'geiger.cpp',
	'health.cpp',
	'hud.cpp',
	'hud_msg.cpp',
	'hud_redraw.cpp',
	'hud_spectator.cpp',
	'hud_update.cpp',
	'in_camera.cpp',
	'input.cpp',
	'input_goldsource.cpp',
	'input_mouse.cpp',
	'input_xash3d.cpp',
	'interpolation.cpp',
	'menu.cpp',
	'message.cpp',
	'parsemsg.cpp',
	'../pm_shared/pm_debug.c',
	'../pm_shared/pm_math.c',
	'../pm_shared/pm_shared.c',
	'saytext.cpp',
	'status_icons.cpp',
	'statusbar.cpp',
	'studio_util.cpp',
	'StudioModelRenderer.cpp',
	'text_message.cpp',
	'train.cpp',
	'tri.cpp',
	'util.cpp',
	'view.cpp',
	'../game_shared/vcs_info.cpp',
	'../public/safe_snprintf.c'
	]

	if bld.env.USE_VGUI:
		defines += ['USE_VGUI']
		libs += ['VGUI']
		source += [
		'vgui_int.cpp',
#		'vgui_ClassMenu.cpp',
		'vgui_ConsolePanel.cpp',
		'vgui_ControlConfigPanel.cpp',
		'vgui_CustomObjects.cpp',
		'vgui_MOTDWindow.cpp',
		'vgui_SchemeManager.cpp',
		'vgui_ScorePanel.cpp',
		'vgui_TeamFortressViewport.cpp',
		'vgui_SpectatorPanel.cpp',
#		'vgui_teammenu.cpp',
		'voice_status.cpp',
		'../game_shared/vgui_checkbutton2.cpp',
		'../game_shared/vgui_grid.cpp',
		'../game_shared/vgui_helpers.cpp',
		'../game_shared/vgui_listbox.cpp',
		'../game_shared/vgui_loadtga.cpp',
		'../game_shared/vgui_scrollbar2.cpp',
		'../game_shared/vgui_slider2.cpp',
		'../game_shared/voice_banmgr.cpp',
		]

		if bld.env.USE_NOVGUI_MOTD:
			defines += ['USE_NOVGUI_MOTD']
			source += ['MOTD.cpp']

		if bld.env.USE_NOVGUI_SCOREBOARD:
			defines += ['USE_NOVGUI_SCOREBOARD']
			source += ['scoreboard.cpp']
	else:
		includes += ['../utils/fake_vgui/include']
		source += [
			'MOTD.cpp',
			'scoreboard.cpp',
		]

	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	if bld.env.GOLDSOURCE_SUPPORT:
		defines += ['GOLDSOURCE_SUPPORT']
		includes += ['../external/']

		if bld.env.DEST_OS == 'win32':
			libs += ["WINMM"]
		else:
			libs += ['DL']

	if 'HAVE_STRLCPY=1' not in defines:
		source += bld.path.parent.ant_glob('external/openbsd/strlcpy.c')

	if 'HAVE_STRLCAT=1' not in defines:
		source += bld.path.parent.ant_glob('external/openbsd/strlcat.c')

	if bld.env.DEST_OS != 'dos' and not bld.env.ANDROID_APK:
		install_path = os.path.join(bld.env.GAMEDIR, bld.env.CLIENT_INSTALL_DIR)
	else:
		install_path = bld.env.PREFIX

	bld.shlib(
		source   = source,
		target   = 'client' + bld.env.POSTFIX,
		name     = 'client',
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		idx = bld.get_taskgen_count()
	)

