#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os

def options(opt):
	grp = opt.add_option_group('Client options')

	grp.add_option('--enable-novgui-motd', action = 'store_true', dest = 'USE_NOVGUI_MOTD', default = False,
		help = 'Prefer non-VGUI MOTD when USE_VGUI is enabled')
	grp.add_option('--enable-novgui-scoreboard', action = 'store_true', dest = 'USE_NOVGUI_SCOREBOARD', default = False,
		help = 'Prefer non-VGUI Scoreboard when USE_VGUI is enabled')
	grp.add_option('--disable-goldsrc-support', action = 'store_false', dest = 'GOLDSOURCE_SUPPORT',
		default=True, help = 'disable GoldSource compatibility on i386 Win/Mac/Linux')

def configure(conf):
	conf.env.USE_NOVGUI_MOTD = conf.options.USE_NOVGUI_MOTD
	conf.env.USE_NOVGUI_SCOREBOARD = conf.options.USE_NOVGUI_SCOREBOARD
	conf.env.USE_VOICEMGR = conf.options.USE_VOICEMGR

	if (conf.env.DEST_CPU == 'x86' or (conf.env.DEST_CPU == 'x86_64' and not conf.options.ALLOW64)) and conf.env.DEST_OS in ['win32', 'linux', 'darwin']:
		conf.env.GOLDSOURCE_SUPPORT = conf.options.GOLDSOURCE_SUPPORT
	else:
		conf.env.GOLDSOURCE_SUPPORT = False

	if conf.env.GOLDSOURCE_SUPPORT and not conf.env.DEST_OS == 'win32':
		conf.check_cc(lib='dl')

def build(bld):
	libs = ['vcs_info']
	defines = ['CLIENT_DLL', 'CLIENT_WEAPONS']
	defines += bld.env.EXPORT_DEFINES_LIST

	# the idea is to always include original vgui headers set (because nobody is gonna port their code to freevgui headers)
	# but compile freevgui as a shared library here so we can link against it, but skip it from install
	includes = ['.',
		'../dlls',
		'../common',
		'../engine',
		'../pm_shared',
		'../game_shared',
		'../public',
		'../utils/vgui/include']
	excluded_files = ['GameStudioModelRenderer_Sample.cpp',
		'game_shared/voice_vgui_tweakdlg.cpp',
		'game_shared/voice_gamemgr.cpp',
		'game_shared/voice_status.cpp']

	defines += ['USE_VGUI']
	libs += ['vgui']
	if bld.env.USE_NOVGUI_MOTD:
		defines += ['USE_NOVGUI_MOTD']
	else:
		excluded_files += ['MOTD.cpp']

	if bld.env.USE_NOVGUI_SCOREBOARD:
		defines += ['USE_NOVGUI_SCOREBOARD']
	else:
		excluded_files += ['scoreboard.cpp']

	source = bld.path.ant_glob('**/*.cpp', excl=excluded_files)
	source += bld.path.parent.ant_glob('game_shared/*.cpp', excl=excluded_files)
	source += bld.path.parent.ant_glob([
		'public/safe_snprintf.c',
		'pm_shared/*.c',
		'dlls/ak47.cpp',
		'dlls/aug.cpp',
		'dlls/awp.cpp',
		'dlls/c4.cpp',
		'dlls/deagle.cpp',
		'dlls/elite.cpp',
		'dlls/famas.cpp',
		'dlls/fiveseven.cpp',
		'dlls/flashbang.cpp',
		'dlls/g3sg1.cpp',
		'dlls/galil.cpp',
		'dlls/glock18.cpp',
		'dlls/hegrenade.cpp',
		'dlls/knife.cpp',
		'dlls/m249.cpp',
		'dlls/m3.cpp',
		'dlls/m4a1.cpp',
		'dlls/mac10.cpp',
		'dlls/mp5navy.cpp',
		'dlls/p228.cpp',
		'dlls/p90.cpp',
		'dlls/rpg.cpp',
		'dlls/rpgrenade.cpp',
		'dlls/scout.cpp',
		'dlls/sg550.cpp',
		'dlls/sg552.cpp',
		'dlls/squeakgrenade.cpp',
		'dlls/tmp.cpp',
		'dlls/tripmine.cpp',
		'dlls/ultimate.cpp',
		'dlls/ump45.cpp',
		'dlls/usp.cpp',
		'dlls/xm1014.cpp',
	])


	if bld.env.DEST_OS == 'win32':
		libs += ['USER32']

	if bld.env.GOLDSOURCE_SUPPORT:
		defines += ['GOLDSOURCE_SUPPORT']
		includes += ['../external/']

		if bld.env.DEST_OS == 'win32':
			libs += ["WINMM"]
		else:
			libs += ['DL']

	if 'HAVE_STRLCPY=1' not in defines:
		source += bld.path.parent.ant_glob('external/openbsd/strlcpy.c')

	if 'HAVE_STRLCAT=1' not in defines:
		source += bld.path.parent.ant_glob('external/openbsd/strlcat.c')

	if bld.env.USE_STATIC_FREEVGUI:
		defines += ['INTERNAL_VGUI_SUPPORT']

	if bld.env.DEST_OS != 'dos' and not bld.env.ANDROID_APK:
		install_path = os.path.join(bld.env.GAMEDIR, bld.env.CLIENT_INSTALL_DIR)
	else:
		install_path = bld.env.PREFIX

	bld.shlib(
		source   = source,
		target   = 'client' + bld.env.POSTFIX,
		name     = 'client',
		features = 'c cxx fix_freevgui_link',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		idx = bld.get_taskgen_count()
	)

