#pragma once
#ifndef ACH_COUNTERS_H
#define ACH_COUNTERS_H

#define ACH_EMPLOYERS_EXPENSE_COUNT 25
#define ACH_SHOOTER_VETERAN_COUNT 3
#define ACH_DECAPITATION_COUNT 25
#define ACH_REDUNANT_COUNT 60
#define ACH_NO_BRAINS_COUNT 125
#define ACH_PUNISHMENT_COUNT 10
#define ACH_DEFORESTATION_COUNT 25
#define ACH_LOW_BATTERY_COUNT 3
#define ACH_MIGHT_MAKES_RIGHT_COUNT 1
#define ACH_WASTE_AMMO_COUNT 5

#endif
