@echo off
echo Setting environment for minimal Visual C++ 6
set INCLUDE=%MSVCDir%\VC98\Include
set LIB=%MSVCDir%\VC98\Lib
set PATH=%MSVCDir%\VC98\Bin;%MSVCDir%\Common\MSDev98\Bin\;%PATH%

echo -- Compiler is MSVC6

set XASH3DSRC=..\..\Xash3D_original
set INCLUDES=-I. -I../common -I../engine -I../pm_shared -I../game_shared -I../public -Igearbox
set SOURCES=gearbox/blkop_apache.cpp ^
	gearbox/blkop_osprey.cpp ^
	gearbox/cleansuit_scientist.cpp ^
	gearbox/ctf_gamerules.cpp ^
	gearbox/ctf_items.cpp ^
	gearbox/ctf_powerups.cpp ^
	gearbox/displacer.cpp ^
	gearbox/drillsergeant.cpp ^
	gearbox/eagle.cpp ^
	gearbox/fgrunt.cpp ^
	gearbox/func_tank_of.cpp ^
	gearbox/gearbox_effects.cpp ^
	gearbox/gearbox_triggers.cpp ^
	gearbox/gearbox_utils.cpp ^
	gearbox/generic_items.cpp ^
	gearbox/geneworm.cpp ^
	gearbox/gonome.cpp ^
	gearbox/grapple_tonguetip.cpp ^
	gearbox/grapple.cpp ^
	gearbox/houndeye_dead.cpp ^
	gearbox/islave_dead.cpp ^
	gearbox/knife.cpp ^
	gearbox/loader.cpp ^
	gearbox/m249.cpp ^
	gearbox/massn.cpp ^
	gearbox/nuclearbomb.cpp ^
	gearbox/op4mortar.cpp ^
	gearbox/otis.cpp ^
	gearbox/penguin.cpp ^
	gearbox/pipewrench.cpp ^
	gearbox/pitdrone.cpp ^
	gearbox/pitworm.cpp ^
	gearbox/recruit.cpp ^
	gearbox/ropes.cpp ^
	gearbox/shock.cpp ^
	gearbox/shockrifle.cpp ^
	gearbox/shockroach.cpp ^
	gearbox/skeleton.cpp ^
	gearbox/sniperrifle.cpp ^
	gearbox/spore_ammo.cpp ^
	gearbox/sporegrenade.cpp ^
	gearbox/sporelauncher.cpp ^
	gearbox/strooper.cpp ^
	gearbox/voltigore.cpp ^
	gearbox/zombie_barney.cpp ^
	gearbox/zombie_soldier.cpp ^
	agrunt.cpp ^
	airtank.cpp ^
	aflock.cpp ^
	animating.cpp ^
	animation.cpp ^
	apache.cpp ^
	barnacle.cpp ^
	barney.cpp ^
	bigmomma.cpp ^
	bloater.cpp ^
	bmodels.cpp ^
	bullsquid.cpp ^
	buttons.cpp ^
	cbase.cpp ^
	client.cpp ^
	combat.cpp ^
	controller.cpp ^
	crossbow.cpp ^
	crowbar.cpp ^
	defaultai.cpp ^
	doors.cpp ^
	effects.cpp ^
	egon.cpp ^
	explode.cpp ^
	flyingmonster.cpp ^
	func_break.cpp ^
	func_tank.cpp ^
	game.cpp ^
	gamerules.cpp ^
	gargantua.cpp ^
	gauss.cpp ^
	genericmonster.cpp ^
	ggrenade.cpp ^
	globals.cpp ^
	glock.cpp ^
	gman.cpp ^
	h_ai.cpp ^
	h_battery.cpp ^
	h_cine.cpp ^
	h_cycler.cpp ^
	h_export.cpp ^
	handgrenade.cpp ^
	hassassin.cpp ^
	headcrab.cpp ^
	healthkit.cpp ^
	hgrunt.cpp ^
	hornet.cpp ^
	hornetgun.cpp ^
	houndeye.cpp ^
	ichthyosaur.cpp ^
	islave.cpp ^
	items.cpp ^
	leech.cpp ^
	lights.cpp ^
	maprules.cpp ^
	monstermaker.cpp ^
	monsters.cpp ^
	monsterstate.cpp ^
	mortar.cpp ^
	mp5.cpp ^
	multiplay_gamerules.cpp ^
	nihilanth.cpp ^
	nodes.cpp ^
	observer.cpp ^
	osprey.cpp ^
	pathcorner.cpp ^
	plane.cpp ^
	plats.cpp ^
	player.cpp ^
	playermonster.cpp ^
	python.cpp ^
	rat.cpp ^
	roach.cpp ^
	rpg.cpp ^
	satchel.cpp ^
	schedule.cpp ^
	scientist.cpp ^
	scripted.cpp ^
	shotgun.cpp ^
	singleplay_gamerules.cpp ^
	skill.cpp ^
	sound.cpp ^
	soundent.cpp ^
	spectator.cpp ^
	squadmonster.cpp ^
	squeakgrenade.cpp ^
	subs.cpp ^
	talkmonster.cpp ^
	teamplay_gamerules.cpp ^
	tempmonster.cpp ^
	tentacle.cpp ^
	triggers.cpp ^
	tripmine.cpp ^
	turret.cpp ^
	util.cpp ^
	weapons.cpp ^
	world.cpp ^
	xen.cpp ^
	zombie.cpp ^
	../pm_shared/pm_debug.c ../pm_shared/pm_math.c ../pm_shared/pm_shared.c
set DEFINES=/DCLIENT_WEAPONS /Dsnprintf=_snprintf /DNO_VOICEGAMEMGR
set LIBS=user32.lib
set OUTNAME=hl.dll
set DEBUG=/debug

cl %DEFINES% %LIBS% %SOURCES% %INCLUDES% -o %OUTNAME% /link /dll /out:%OUTNAME% %DEBUG% /def:".\hl.def"

echo -- Compile done. Cleaning...

del *.obj *.exp *.lib *.ilk
echo -- Done.
