#! /usr/bin/env python
# encoding: utf-8
# a1batross, mittorn, 2018

from waflib import Utils
import os

def options(opt):
	return

def configure(conf):
	if conf.env.COMPILER_CC == 'msvc':
		# hl.def removes MSVC function name decoration from GiveFnptrsToDll on Windows.
		# Without this, the lookup for this function fails.
		hlDefNode = conf.path.find_resource("./hl.def")

		if hlDefNode is not None:
			conf.env.append_value('LINKFLAGS', '/def:%s' % hlDefNode.abspath())
		else:
			conf.fatal("Could not find hl.def")

def build(bld):
	excluded_files = ['agrunt.cpp',
			'airtank.cpp',
			'aflock.cpp',
			'apache.cpp',
			'barnacle.cpp',
			'barney.cpp',
			'bigmomma.cpp',
			'bloater.cpp',
			'bullsquid.cpp',
			'controller.cpp',
			'crossbow.cpp',
			'crowbar.cpp',
			'defaultai.cpp',
			'egon.cpp',
			'flyingmonster.cpp',
			'func_tank.cpp',
			'gargantua.cpp',
			'gauss.cpp',
			'genericmonster.cpp',
			'ggrenade.cpp',
			'glock.cpp',
			'gman.cpp',
			'h_battery.cpp',
			'h_cine.cpp',
			'h_cycler.cpp',
			'handgrenade.cpp',
			'hassassin.cpp',
			'headcrab.cpp',
			'healthkit.cpp',
			'hgrunt.cpp',
			'hornet.cpp',
			'hornetgun.cpp',
			'houndeye.cpp',
			'ichthyosaur.cpp',
			'islave.cpp',
			'items.cpp',
			'leech.cpp',
			'monstermaker.cpp',
			'monsterstate.cpp',
			'mortar.cpp',
			'mp5.cpp',
			'nihilanth.cpp',
			'nodes.cpp',
			'observer.cpp',
			'osprey.cpp',
			'python.cpp',
			'rat.cpp',
			'roach.cpp',
			'rpg.cpp',
			'satchel.cpp',
			'scientist.cpp',
			'scripted.cpp',
			'shotgun.cpp',
			'soundent.cpp',
			'squadmonster.cpp',
			'squeakgrenade.cpp',
			'talkmonster.cpp',
			'tempmonster.cpp',
			'tentacle.cpp',
			'tripmine.cpp',
			'turret.cpp',
			'xen.cpp',
			'zombie.cpp',
			'stats.cpp',
			'Wxdebug.cpp']

	source = bld.path.ant_glob('**/*.cpp', excl=excluded_files)
	source += bld.path.parent.ant_glob([
					'pm_shared/*.c',
					'public/safe_snprintf.c',
					'game_shared/voice_gamemgr.cpp'
					])

	defines = bld.env.EXPORT_DEFINES_LIST
	if 'HAVE_STRLCPY=1' not in defines:
		source += bld.path.parent.ant_glob('external/openbsd/strlcpy.c')

	if 'HAVE_STRLCAT=1' not in defines:
		source += bld.path.parent.ant_glob('external/openbsd/strlcat.c')

	includes = [
		'.',
		'../common',
		'../engine',
		'../pm_shared',
		'../game_shared',
		'../public',
		'dmc',
		'aghl',
		'3wave',
		'..']

	if bld.env.DEST_OS != 'dos' and not bld.env.ANDROID_APK:
		install_path = os.path.join(bld.env.GAMEDIR, bld.env.SERVER_INSTALL_DIR)
	else:
		install_path = bld.env.PREFIX

	if bld.env.DEST_OS == 'darwin' and bld.env.SERVER_LIBRARY_NAME_OSX:
		# on Apple platforms we always use gamedll_osx liblist/gameinfo key, if it's set
		server_dll_name = bld.env.SERVER_LIBRARY_NAME_OSX
	elif bld.env.DEST_OS != 'win32' and bld.env.SERVER_LIBRARY_NAME_LINUX:
		# on non-Windows platforms we use gamedll_linux liblist/gameinfo key, if it's set
		server_dll_name = bld.env.SERVER_LIBRARY_NAME_LINUX
	else:
		# on Windows or if no gamedll_osx or gamedll_linux is set, use default gamedll key
		server_dll_name = bld.env.SERVER_LIBRARY_NAME

	bld.shlib(
		source   = source,
		target   = server_dll_name + bld.env.POSTFIX,
		name     = 'server',
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = 'vcs_info',
		install_path = install_path,
		idx = bld.get_taskgen_count()
	)
